version: '3.5'

networks:
  app-net:
    driver: bridge

services:
  nginx:
    container_name: nginx-timemap
    image: bitnami/nginx:${NGINX_VERSION}-${OS_VERSION}
    restart: always
    environment:
      - 'TZ=${TIMEZONE}'
    networks:
      - app-net
    ports: 
      - "80:8081"
      - "443:8443"
    volumes:
      - ./public-html:/app:rw
      - ./config/nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:rw
      - ./config/nginx/vhost:/opt/bitnami/nginx/conf/vhosts:rw
      - ./logs/nginx/${NGINX_VERSION}:/opt/bitnami/nginx/logs:rw
    links:
      - redis
      - app-test
      - db-test

  redis:
    build: ./redis
    container_name: redis-server
    restart: always
    tty: true
    ports:
      - "6379:6379"
    working_dir: /data
    volumes:
      - ./etc/localtime:/etc/localtime
    networks:
      - app-net

  app-test:
    image: pakde:php4-fpm-v2
    container_name: app-test
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./public-html:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-net

  db-test:
    image: mysql:5.7
    container_name: db-test
    restart: unless-stopped
    tty: true
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admintest
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-net
